### ISSUE TITLE
Fix the upgrading path

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/LibPlayerSpells-1.0#100]
We need to handle upgrading the tables we attach to the lib object in case of multiple different instances of LibPlayerSpells.

**Comment by Adirelle** [comment]
Do we really need to upgrade them ? I mean: if the previous version of LibPlayerSpells is too old (e.g. anterior to the version where the new format was introduced), just wipe the tables and start over with the new data.

**Comment by Rainrider** [comment]
Yes, I thought exactly about that. Currently there is no such a check in place.

**Comment by Adirelle** [comment]
Which commit broke the API/data format and which was the library version before and after ?

**Comment by Rainrider** [comment]
Closed with a2c474a1fc750514170145e9328c240180062d4c
