### ISSUE TITLE
Add Sins of the Many to the priest database

### ISSUE THREAD

**Issue by gagou** [AdiAddons/LibPlayerSpells-1.0#109]
"Sins of the many" is a discipline priest artifact golden trait.
The spell id of the trait is 198074
The buff provided by the spell is 198076

**Comment by Rainrider** [comment]
@gagou could you paste me a dump of UnitAura for this buff? Maybe a custom rule displaying the % increase as if it was a stack will be a good fit here.

**Comment by gagou** [comment]
Here is a dump for this buff in french
Dump: value=UnitAura('player', 5)
[1]="Les péchés de tous",
[2]="",
[3]="Interface\\Icons\\Spell_Holy_HolyGuidance",
[4]=1,
[6]=0,
[7]=0,
[8]="player",
[9]=false,
[10]=false,
[11]=198076,
[12]=false,
[13]=false,
[14]=true,
[15]=false,
[16]=1,
[17]=1

thanks for the update of LibPlayerSpell

**Comment by Rainrider** [comment]
Ah, Sins of the Many is actually a passive trait. So no need for a special ABA rule here. Thanks for the dump though!
