### ISSUE TITLE
Spells removed in 7.1

### ISSUE THREAD

**Issue by nebularg** [AdiAddons/LibPlayerSpells-1.0#110]
1x LibPlayerSpells-1.0-9: 4 errors in HUNTER database:
Data are probably outdated: data version=70000, client version=70100
Spell #204321: unknown spell
Spell #204324: unknown spell
Spell #204333: unknown spell

1x LibPlayerSpells-1.0-9: 3 errors in PALADIN database:
Data are probably outdated: data version=70000, client version=70100
Spell #202270: unknown spell
Spell #205656: unknown provider spell

**Comment by Rainrider** [comment]
7.1 is not yet released in Europe. I'll have a look tomorrow.

**Comment by nebularg** [comment]
Pretty annoying you throw errors for this.

**Comment by nebularg** [comment]
I appreciate that. Now it would be nice if the fixes were getting pushed to wowace so I could use them 😝

**Comment by Rainrider** [comment]
Done
