### ISSUE TITLE
Missed druid spell - Lifebloom modified by talent Undergrowth

### ISSUE THREAD

**Issue by xizar** [AdiAddons/LibPlayerSpells-1.0#157]
When the talent Undergrowth (392301) is taken, Lifebloom (33763) is replaced by Lifebloom (188550).

I don't know if it's the correct way to "fix" this, but inserting a second spellid in the HELPFUL section for druids (line 174 in data\Druid.lua) fixes this.

			188550, -- Lifebloom (Restoration talent - Undergrowth)

I know jack-all about updating the file for github myself, so I hope someone can make the fix.

**Comment by Rainrider** [comment]
I am closing this since the prepatch for the next expansion has been released and class data changed. Due to lack of contributions class data is now quite stale.
