### ISSUE TITLE
data/Evoker.lua:25: LibPlayerSpells-1.0: invalid category: "EVOKER"

### ISSUE THREAD

**Issue by nebularg** [AdiAddons/LibPlayerSpells-1.0#158]
Library doesn't upgrade to include the EVOKER category if you have an old version.

Should probably update https://github.com/AdiAddons/LibPlayerSpells-1.0/blob/master/LibPlayerSpells-1.0.lua#L27 to be `if oldMinor and oldMinor < 13 then`

**Comment by Rainrider** [comment]
Thank you for the pointer @nebularg, should be fixed with 4e49e899b0025a7e2fea6c59f71dbb1ce035e375
