### ISSUE TITLE
Snares, sprints and DR spells ?

### ISSUE THREAD

**Issue by Adirelle** [AdiAddons/LibPlayerSpells-1.0#44]
Should I add Snares and sprints (e.g. temporary moving speed alterations) ? I am also considering dropping DRData support and dispatching all its data into LPS. 

I think it would ease maintaining it by gathering all the data in one library, but yet keeping a list per class.

Any thought ?

**Comment by Rainrider** [comment]
Diminishing returns categories that can be tracked by using UNIT_AURA are now part of LPS under the special category CROWD_CTRL. AdiButtonAuras now pulls its DR data from LPS and support for DRData-1.0 has been dropped.

Knockbacks (KNOCKBACK) and Silences (INTERRUPT) are ordinary flags. Snares are also an ordinary flag (SNARE). Knockbacks and snares are either not yet or just partially tagged.

**Comment by Adirelle** [comment]
This is actually fine. It eased the integration into oUF_Adirelle so I could drop the dependency to DRData-1.0.
