### ISSUE TITLE
Legion Support

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/LibPlayerSpells-1.0#82]
#As all of the classes were revamped for the next expansion, I removed all the WoD spell data.

#### Current data status:
**Death Knight:**
  - [x] Blood core abilities and talents
  - [x] Frost core abilities and talents
  - [x] Unholy core abilities and talents
  - [x] Artifacts

**Demon Hunter:**
  - [x] Vengeance core abilities and talents
  - [x] Havoc core abilities and talents
  - [x] Artifacts

**Druid:**
  - [x] Balance core abilities and talents
  - [x] Feral core abilities and talents
  - [x] Guardian core abilities and talents
  - [x] Restoration core abilities and talents
  - [x] Artifacts

**Hunter:**
  - [x] Beast Master core abilities and talents
  - [x] Marksmanship core abilities and talents
  - [x] Survival core abilities and talents
  - [x] Artifacts
  - [x] Pet spells

**Mage:**
  - [x] Arcane core abilities and talents
  - [x] Fire core abilities and talents
  - [x] Frost core abilities and talents
  - [x] Artifacts

**Monk:**
  - [x] Brewmaster core abilities and talents
  - [x] Mistweaver core abilities and talents
  - [x] Windwalker core abilities and talents
  - [x] Artifacts

**Paladin:**
  - [x] Holy core abilities and talents
  - [x] Protection core abilities and talents
  - [x] Retribution core abilities and talents
  - [x] Artifacts

**Priest:**
  - [x] Discipline core abilities and talents
  - [x] Holy core abilities and talents
  - [x] Shadow core abilities and talents
  - [x] Artifacts

**Rogue:**
  - [x] Assassination core abilities and talents
  - [x] Outlaw core abilities and talents
  - [x] Subtlety core abilities and talents
  - [x] Artifacts

**Shaman:**
  - [x] Elemental core abilities and talents
  - [x] Enhancement core abilities and talents
  - [x] Restoration core abilities and talents
  - [x] Artifacts

**Warlock:**
  - [x] Affliction core abilities and talents
  - [x] Demonology core abilities and talents
  - [x] Destruction core abilities and talents
  - [x] Artifacts

**Warrior:**
  - [x] Arms core abilities and talents
  - [x] Fury core abilities and talents
  - [x] Protection core abilities and talents
  - [x] Artifacts

If someone would like to contribute, please include all spell data you may found, including crowd control abilities. Use Lua comments to tag DR categories for spells, if you know them.

**Comment by dafzor** [comment]
Could alpha pushes of AdiButtonAuras be made with what we have at the moment, unless users comes to github the released version doesn't do much.

**Comment by Rainrider** [comment]
I can't push ABA without code changes. Instead I have to create a tag so the packager picks up library changes which translates to tagging the same commit over and over. Also most people use the curse client, which does not pick alpha versions (correct me if I'm wrong). It also does not pick beta versions by default, but apparently there is an option for that.

I would tag betas when we have a complete data set for a given class (except for honor talents, since those come with Legion). Basically alpha means "data is incomplete", beta means "data is there, please review". I hope this will reduce the number of iterations on a single class.

For now just install the alpha version of LPS from wowace by hand as a stand-alone addon. ABA will use the spells with the highest revision number.

**Comment by dafzor** [comment]
Curse client allows you to set preference for Release, Beta or Alpha versions globally and per addon, I keep mine usually at beta unless there's an addon that delays releases in alpha. However I believe you can push betas and alphas into the website frontpage, and for addons like adibuttonAuras that i know are being worked on at alpha.

I wasn't thinking of myself in the comment above but the average user that's only familiar with curse website/client. While LibPlayerSpells is far from complete what's there is certainly better then nothing and for those that depend on this addon it might make all the difference.

PS: I did notice you did a beta push, so thank you for that.

**Comment by arcadepro** [comment]
I've already done the Prot Warrior stuff locally. I'll merge it when I re-install git and remember how to use it. :P

**Comment by dafzor** [comment]
@arcadepro you don't need git, I've not been using it at all, I just open the file go to the file page on github press the little pencil and it makes a branch, I paste in my changes, add a message and then commit and request a pull.

This is the simplest way I know to contribute even though it means I keep posponing actually learning git.

**Comment by dafzor** [comment]
@Rainrider git is not a simple tool specially when it comes to providing a clean patch, just look at how @arcadepro latest pull request ended up with a bunch of "extra stuff" that wasn't supposed to be there.

Through the web interface with a single click git will clone the rep and create a branch with just the changes done to that single file, meaning the pull request is as clean as it get. It's simple enough that even someone totally unfamiliar with git would be able to contribute.

I eventually did get the commit message fixed on the first PR branch, but like I said in the interest of having the changes integrated asap making a new PR was just simpler and easier.

**Comment by arcadepro** [comment]
The extra changes were pulled in because I used the adi/legion branch (as told to do so above). I would not normally do this but I assumed there was some reason for it.

**Comment by Rainrider** [comment]
@arcadepro sorry my bad. The issue here was opened before the pre-patch came. Since the pre-patch I merged the legion branch into master, so this is where development happens right now.

@dafzor I do not share the philosophy that anything is better than nothing.

**Comment by Pandha** [comment]
Hey,
I edited the "AdiButtonAuras\libs\LibPlayerSpells-1.0\data\Warrior.lua"-File to cover the Fury Warrior. Sometimes there are multiple auras, that effect one skill (ie. Bloodthrist), and I don't know how you handle it normally. But I've done it, like I would prefere it. Maybe you should double check this first.

Unfortunately I have no experience with GitHub, so I copied the code in pastebin.
http://pastebin.com/w0J7r44L

Hopefully it helps you guys, you do a great work!

**Comment by Rainrider** [comment]
@Pandha I'll take a look later today. Thank you for the the contribution.

**Comment by Rainrider** [comment]
Most of the submitted data has been reviewed. Please consider the following for future and unmerged submissions:

Providers are the spells that make a certain aura possible, not necessarily the spells that apply the aura. I.e. the fury warrior talent Bounding Stride (202163) modifies Heroic Leap (6544) so that it applies the personal buff Bounding Stride (202164). So, 202164 is the aura (category COOLDOWN AURA PERSONAL, because Heroic Leap has a 30 sec. CD), 202163 is the provider and 6544 is the modified spell. The reason to do it like this is to be able to react if the provider becomes unknown (ABA deactivates the rule).

Also in some cases the provider and the aura both have the same ID, but the modified spell is a different one. The default behavior for ABA is to use the auraID as the providerID if it is not explicitly given. I.e. the arms warrior talent Focused Rage (207982) provides the buff Focused Rage (207982) which in turn modifies Mortal Strike (12294). If you map MS as provider to FR the rule will be active as long as MS is known, regardless of whether FR is known or not. The better way to map it is to not explicitly state a provider for FR (since it is the same as the auraID) and do the mapping of the FR to MS in the table containing the aura to modified spells associations.

Another thing missing in most of the submission are crowd control abilities. Please do not just add the stuff that does not lite up on your bars. DRData is just partially updated and actually pending removal. Please include diminishing returns category as a Lua comment or at least add the CC abilities for the spec.

Cooldowns are another thing. LPS is not just a backend for ABA. Addons can use it to tell stuff like "Did a tank used their survival cooldowns". So please do add abilities that have a CD even if there is no aura associated with those. I would say that a CD is everything above 3s, which is certainly too low for most uses, but let's just keep the possibility for people to use the data if they want to.

**Comment by arcadepro** [comment]
Ok, thanks for the explanation.
